"""agg codigo de verificacion empresa

Revision ID: 079bdce8d45c
Revises: 145660ebb6ce
Create Date: 2025-05-24 12:08:41.150236

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '079bdce8d45c'
down_revision = '145660ebb6ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.Integer()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
