"""Agregar cambios en empleado

Revision ID: 145660ebb6ce
Revises: 56941d515f37
Create Date: 2025-05-21 11:00:40.524868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '145660ebb6ce'
down_revision = '56941d515f37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=128)))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')

    # ### end Alembic commands ###
