"""añadir metodo to dict

Revision ID: 941b968c65eb
Revises: 6f971c7be573
Create Date: 2025-05-18 15:15:45.454305

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '941b968c65eb'
down_revision = '6f971c7be573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_bank_account_number', ['account_number'])
        batch_op.create_unique_constraint('uq_bank_bank_name', ['bank_name'])
        batch_op.create_unique_constraint('uq_bank_nit', ['nit'])

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_company_email', ['email'])
        batch_op.create_unique_constraint('uq_company_name', ['name'])
        batch_op.create_unique_constraint('uq_company_nit', ['nit'])

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_employee_email', ['email'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_role_name', ['name'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_email', type_='unique')

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_constraint('uq_role_name', type_='unique')

    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.drop_constraint('uq_employee_email', type_='unique')

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_constraint('uq_company_nit', type_='unique')
        batch_op.drop_constraint('uq_company_name', type_='unique')
        batch_op.drop_constraint('uq_company_email', type_='unique')

    with op.batch_alter_table('bank', schema=None) as batch_op:
        batch_op.drop_constraint('uq_bank_nit', type_='unique')
        batch_op.drop_constraint('uq_bank_bank_name', type_='unique')
        batch_op.drop_constraint('uq_bank_account_number', type_='unique')

    # ### end Alembic commands ###
